### PR TITLE
Implement better support for SAF

### LINKED ISSUE #475: better access of files with SAF
**Feature description**

termux-manage-folder: open a directory tree and returns the URI.  
termux-saf-ls: lists directories and files in a folder as JSON, returning the URI and metadata, so you can navigate the document tree.  
termux-saf-read: Reads a file from a URI and outputs it to stdout or a file.  
termux-saf-write: Writes stdin to a file from a URI, or to a new file if the parent directory URI and a name is specified.  

Example: `termux-saf-read <URI to file on the sd card> | gzip | termux-saf-write <URI to folder on the sd card> compressed.gz`

Another usage case for the user could be to periodically backup the home directory, compress it, encrypt it and safe it to google drive via SAF, completely automatic and without having to choose any location or moving the file yourself.  

The difference to `termux-storage-get` is that the files don't need to be saved temporarily, so you can use streaming programs to process large files efficiently, and because the app gets the permission to use the directory tree forever, there is no need to open a UI when a command is run, you can automate reading and writing from the SAF from the command line.  

You could also then make more high-level programs to build on top of that, e.g. storing all accessible folder URIs in a file and map them to paths and make utilities to work with those paths instead that internally call the URI-based programs, abstracting away the URIs and working with paths like `dir1/some/folders/deep/file.txt`, which is easier for the user to type.

It may also be possible to modify proot to "mount" a SAF directory, so you can access the files with programs that can't operate with stdin and stdout.

**Reference implementation**

Have you checked if the feature is accessible through the Android API?
https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE  
https://developer.android.com/training/data-storage/shared/documents-files

Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)  
[simple file manager](https://github.com/SimpleMobileTools/Simple-File-Manager) uses that to get access to the sd card.

### PR DESCRIPTION
**Pull request by tareksander**
I implemented an interface to give Termux:API access to folders via SAF, list those folders, the contents, subfolders, create, delete, read and write files.  
  
I also [made a branch in my termux-api-package fork](https://github.com/tareksander/termux-api-package/tree/saf) with utilities to use this new interface from the terminal.

This will close #475.

### CODE REVIEW

**Comment by Grimler91** [comment]
The non-json printed results are printed without a trailing newlines, is that on purpose?

```
~/projects/termux-api-package $ termux-saf-managedir
content://com.android.externalstorage.documents/tree/primary%3A~/projects/termux-ap
```

**Comment by tareksander** [comment]
I thought that would be nice if you capture the output directly into a variable and not get the newline, but a JSON string and after that a newline is fine, too. Should I do that instead?

**Comment by agnostic-apollo** [comment]
Yes, newlines should exist for both json and normal string output so that `PS1` is not on the same line after command is run. That's how commands normally behave.

Command Substitution like `var="$(command)"` will automatically trim any newlines, its standard shell behaviour, so not an issue for var capture.

>The shell shall expand the command substitution by executing command in a subshell environment (see Shell Execution Environment) and replacing the command substitution (the text of command plus the enclosing "$()" or backquotes) with the standard output of the command, **removing sequences of one or more `<newline>` characters at the end of the substitution**. Embedded `<newline>` characters before the end of the output shall not be removed; however, they may be treated as field delimiters and eliminated during field splitting, depending on the value of IFS and quoting that is in effect. If the output contains any null bytes, the behavior is unspecified.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03

**Comment by tareksander** [comment]
Fixed that now.

**Pull request merged**
