### PR TITLE
MicRecoderAPI: a few enhancements

### PR DESCRIPTION
**Pull request by tomty89**
Ready to be merged

### CODE REVIEW

**Comment by tomty89** [comment]
Okay just passed a build test. @fornwall should be ready for you to review. I can do some run tests if you can provide me with a test build. (Sorry, still figuring out the signing stuff.)

**Comment by fornwall** [comment]
@tomty89 I think the best alternative is for you to uninstall all Termux apps and then install them from source, which allows you to use your own signature (just launching the app as any else from within Android Studio). Would that work for you for testing? You can ping me on gitter if you need to discuss it!

**Comment by tomty89** [comment]
@fornwall Oh never mind, I didn't even recall the fact that Termux "official" builds are signed by Google and F-Droid respectively. Silly me. Anyway I found a tutorial (on [Microsoft](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/manually-signing-the-apk), lol) on how to sign the apks myself with a couple commands. Should be able to test it myself soon :-D

**Comment by tomty89** [comment]
@fornwall Should be good enough to be merged, thanks!

**Pull request merged**
