### PR TITLE
Create ProximityAPI.java

### PR DESCRIPTION
**Pull request by Auxilus**

### CODE REVIEW

**Comment by Auxilus** [comment]
Unlike https://github.com/termux/termux-api/pull/101 in this PR `mSensorManager.registerListener(this, mProximity, SensorManager.SENSOR_DELAY_NORMAL);` will call the sensor to listen and unregister it as soon as the task is finished.

**Comment by fornwall** [comment]
Looks promising! Is this missing code though? I don't see where the `event` variable is declared.

**Comment by fornwall** [comment]
Also, I think we should just return the distance in centimeters instead of just "Near" and "Far" - so perhaps `out.name("distance").value(event.values[0]);`?

**Comment by Auxilus** [comment]
@fornwall check now..

**Comment by Auxilus** [comment]
I guess we can access the values by `sensorEvent.values[0]`

**Comment by Auxilus** [comment]
closing in favor of https://github.com/termux/termux-api/pull/147

**Pull request closed without merging**
