### PR TITLE
Implemented Sensor API

### PR DESCRIPTION
**Pull request by PeratX**
Now you can execute ``` ./../usr/libexec/termux-api SensorProximity``` in ```~``` to get the proximity sensor's data.
If you have accepted my coding format, I can implement more sensors.

Sensors available:
* Accelerometer
* Ambient Temperature
* Light
* Releative Humidity
* Pressure
* Proximity

#58 #59 & README Todo list

### CODE REVIEW

**Comment by PeratX** [comment]
@fornwall Please have a review. Thanks.

**Comment by PeratX** [comment]
@fornwall Please have a review. Thanks.

**Comment by PeratX** [comment]
@fornwall Please have a review. Thanks.

**Comment by fornwall** [comment]
Interesting!

About `TermuxAPI extends Application` and calling `sensorAPI = new SensorAPI(this);` in the application `onCreated()`: This will always cause the sensor being monitored continuously as soon as the app starts, even if no sensor API call is used. Would it be possible to change it to only listen for a sensor event when the API request comes in, and the cancel the listening when the desired sensor event is received?

**Comment by PeratX** [comment]
It will need thread sync. Because you cannot get a listener data directly.

**Pull request closed without merging**
