### PR TITLE
AudioAPI: avoid redundant code

### PR DESCRIPTION
**Pull request by tomty89**

### CODE REVIEW

**Comment by fornwall** [comment]
Thanks!

**Comment by tomty89** [comment]
No, it's just because (if I am not missing anything else) `bs` is defined in the if. Should be fine if we take it out.

Btw why all the `final`s?

**Comment by its-pointless** [comment]
It won't compile... i was in a hurry.

On 24 Mar. 2018 9:50 am, "tomty89" <notifications@github.com> wrote:

No, it's just because (if I am not missing anything else) bs is defined in
the if. Should be fine if we take it out.

Btw why all the finals?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-api/pull/134#issuecomment-375818482>, or mute
the thread

**Comment by tomty89** [comment]
Wait a second is the error you posted build time error or runtime error (that seen only on older device)?

Does it change anything if you keep the structure but just change `getBufferSizeInFrames` to `getSampleRate`?

**Comment by its-pointless** [comment]
build time 
and it makes no difference

**Comment by tomty89** [comment]
```
$ tree -a com/
com/
└── termux
    └── api
        ├── AudioAPI.java
        ├── TermuxApiReceiver.java
        └── util
            ├── ResultReturner.java
            ├── TermuxApiLogger.java
            └── TermuxApiPermissionActivity.java

3 directories, 5 files
```
```
$ cat com/termux/api/TermuxApiReceiver.java
package com.termux.api;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

import com.termux.api.util.TermuxApiLogger;

public class TermuxApiReceiver extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        String apiMethod = intent.getStringExtra("api_method");
        if (apiMethod == null) {
            TermuxApiLogger.error("Missing 'api_method' extra");
            return;
        }

        switch (apiMethod) {
            case "AudioInfo":
                AudioAPI.onReceive(this, context, intent);
                break;
            default:
                TermuxApiLogger.error("Unrecognized 'api_method' extra: '" + apiMethod + "'");
        }
    }

}
```
```
$ git diff com/termux/api/AudioAPI.java
diff --git a/app/src/main/java/com/termux/api/AudioAPI.java b/app/src/main/java/com/termux/api/AudioAPI.java
index acf87ed..7e13c2d 100644
--- a/app/src/main/java/com/termux/api/AudioAPI.java
+++ b/app/src/main/java/com/termux/api/AudioAPI.java
@@ -23,6 +23,7 @@ public class AudioAPI {
         final boolean bluetootha2dp = am.isBluetoothA2dpOn();
         final boolean wiredhs = am.isWiredHeadsetOn();
         final int nativeoutput = AudioTrack.getNativeOutputSampleRate(AudioManager.STREAM_MUSIC);
+       int _bs = 0;
         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
             AudioTrack at = new AudioTrack(
                 new AudioAttributes.Builder()
@@ -34,11 +35,12 @@ public class AudioAPI {
                 AudioTrack.MODE_STREAM,
                 AudioManager.AUDIO_SESSION_ID_GENERATE
             );
-            final int bs = at.getBufferSizeInFrames();
+            _bs = at.getBufferSizeInFrames();
             //final int bc = at.getBufferCapacityInFrames(); only available api 24 and up and apparently
             // always returns same value as the initial getbuffersizeinframes.
             at.release();
         }
+       final int bs = _bs;

         ResultReturner.returnData(apiReceiver, intent, new ResultReturner.ResultJsonWriter() {
             public void writeJson(JsonWriter out) throws Exception {
```
```
$ ecj com/
----------
1. WARNING in /data/data/com.termux/files/home/termux-api/app/src/main/java/com/termux/api/AudioAPI.java (at line 23)
        final boolean bluetootha2dp = am.isBluetoothA2dpOn();
                                         ^^^^^^^^^^^^^^^^^^^
The method isBluetoothA2dpOn() from the type AudioManager is deprecated
----------
2. WARNING in /data/data/com.termux/files/home/termux-api/app/src/main/java/com/termux/api/AudioAPI.java (at line 24)
        final boolean wiredhs = am.isWiredHeadsetOn();
                                   ^^^^^^^^^^^^^^^^^^
The method isWiredHeadsetOn() from the type AudioManager is deprecated
----------
2 problems (2 warnings)
$
```

Not sure if it's the best way coz it still looks a bit stupid to me, but at least it should work for now.

**Comment by tomty89** [comment]
Sorry for not doing a build test before making the PR btw. Don't have a PC and didn't thought of testing it like this on Termux.

**Pull request merged**
