### PR TITLE
Update WiFiAPI to check if geolocate is enabled

### PR DESCRIPTION
**Pull request by Auxilus**
Fix for https://github.com/termux/termux-packages/issues/1694

### CODE REVIEW

**Comment by xeffyr** [comment]
You should import LocationManager:
```
import android.location.LocationManager;
```
Or there will be error: cannot find symbol class LocationManager

**Comment by Auxilus** [comment]
@xeffyr done

**Comment by Auxilus** [comment]
Will it work btw?

**Comment by Auxilus** [comment]
Cz i don't have that much knowledge about java and app development

**Comment by xeffyr** [comment]
I have checked - it works.

**Comment by Auxilus** [comment]
Nice to hear that!

**Comment by fornwall** [comment]
Sorry for letting this linger so long!

After https://github.com/termux/termux-api/commit/de8d68a64e38ac8b8d5c0bd1799e571604b53b6e we now show `Location needs to be enabled on the device` if termux-wifi-scaninfo is called when Location is disabled on the device.

The other change, handling `info.getSupplicantState().toString() == "SCANNING"` as an error, should probably not be applied (the supplicant state is already exposed by the API as a field, so better to be handled by users).

**Pull request closed without merging**
